import { Hind_Siliguri } from "next/font/google";

import "./globals.css";
import "./app.css";
import Footer from "./components/shared/footer/Footer";

const hindSiliguri = Hind_Siliguri({
  subsets: ["bengali"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={hindSiliguri.className}>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
